name: pathify
version: 0.0.1
description: Make Dart dependencies live
dependencies:
  ansicolor: ">=0.0.9 <0.1.0"
  args: ">=0.12.1 <0.14.0"
  path: "^1.3.6"
  yaml: any
environment:
  sdk: ">1.12.0"
executables:
  pathify:
