name: pathify
version: 0.1
description: Make Dart dependencies live
dependencies:
  ansicolor: ">=0.0.9 <0.1.0"
  barback: '>=0.15.0 <0.16.0'
  dart_style: "any"
  vacuum_persistent: "^2.0.0"
  avl_tree: "0.1.1+1"
  dartlings: "^0.2.0"
  quiver: "^0.21.4"
  json_schema: "1.0.1"
  quiver: any
  args: ">=0.12.1 <0.14.0"
  path: "^1.3.6"
  dartson: "^0.2.5"
  yaml: any
environment:
  sdk: ">1.12.0"
executables:
  pathify:
